export const selectedSupplierData = [
  {
    projectId: "1",
    id: 1,
    image: "Image 1",
    vehicleCount: 100,
    modelCount: 13,
    productCount: 13,
    openIssues: 10,
    closedIssues: 23,
    onTrack: 2,
    behind: 1,
  },
  {
    projectId: "1",
    id: 2,
    image: "Image 2",
    vehicleCount: 200,
    modelCount: 25,
    productCount: 20,
    openIssues: 20,
    closedIssues: 30,
    onTrack: 1,
    behind: 3,
  },
  {
    projectId: "1",
    id: 3,
    image: "Image 3",
    vehicleCount: 300,
    modelCount: 30,
    productCount: 35,
    openIssues: 15,
    closedIssues: 25,
    onTrack: 4,
    behind: 2,
  },
  {
    projectId: "2",
    id: 4,
    image: "Image 4",
    vehicleCount: 400,
    modelCount: 40,
    productCount: 40,
    openIssues: 12,
    closedIssues: 28,
    onTrack: 3,
    behind: 1,
  },
  {
    projectId: "2",
    id: 5,
    image: "Image 5",
    vehicleCount: 500,
    modelCount: 50,
    productCount: 45,
    openIssues: 18,
    closedIssues: 32,
    onTrack: 2,
    behind: 2,
  },
  {
    projectId: "3",
    id: 6,
    image: "Image 6",
    vehicleCount: 600,
    modelCount: 60,
    productCount: 50,
    openIssues: 15,
    closedIssues: 25,
    onTrack: 5,
    behind: 1,
  },
  {
    projectId: "3",
    id: 7,
    image: "Image 7",
    vehicleCount: 700,
    modelCount: 70,
    productCount: 60,
    openIssues: 10,
    closedIssues: 30,
    onTrack: 4,
    behind: 2,
  },
  {
    projectId: "4",
    id: 8,
    image: "Image 8",
    vehicleCount: 800,
    modelCount: 80,
    productCount: 65,
    openIssues: 20,
    closedIssues: 35,
    onTrack: 3,
    behind: 3,
  },
  {
    projectId: "4",
    id: 9,
    image: "Image 9",
    vehicleCount: 900,
    modelCount: 90,
    productCount: 70,
    openIssues: 25,
    closedIssues: 30,
    onTrack: 2,
    behind: 4,
  },
];
